local space_pressed = false

function init(self)
	self.dir = vmath.vector3()
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
	local current_position = go.get_position()

	local new_position = current_position + self.dir * 500 * dt

	go.set_position(new_position)

	self.dir = vmath.vector3()
end

function on_input(self, action_id, action)
	local position = go.get_position()
	if action_id == hash("left") then
		if position.x > 80 then
			self.dir.x = -1
		end
	elseif action_id == hash("right") then
		if position.x < 960 - 80 then
			self.dir.x = 1
		end
	end
	if action_id == hash("space") then
		if action.pressed then
			msg.post("/ball", hash("space_pressed"))
		end
	end
end
